# Site settings
title: Elena Yan
SEOTitle: Elena Yan
header-img: img/bg-library.jpeg
email: elena.yan@emse.fr
description: "Elena Yan's Personal Website."
keyword: "Elena Yan, EY, Computer Science, Multi-Agent Systems, Normative Multi Agent System, Self-Adaptation, MINES Saint Etienne, Unibo"
url: "http://yan-elena.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yan-elena/yan-elena.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Every failure is leading towards success."
sidebar-avatar: /img/about-ey-rect.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    yan-elena
linkedin_username:  elena-yan-711603271
google_scholar:     https://scholar.google.com/citations?user=4ROQqgsAAAAJ&hl=en
orcid:              0009-0000-6660-9378


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
pagination:
  enabled: true
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "vendor"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-scholar


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

scholar:
  last_name: [Yan]
  first_name: [Elena]
  style: apa
  locale: en
  source: ./_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"